apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: docker-demo
        image: 1a2k3m/docker-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
      nodeSelector:
        kubernetes.io/hostname= gke-testkubernetes-pool-1-82ec098f-f8zz
