apiVersion: v1
kind: Pod
metadat:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
    spec:
      container:
      - name: k8s-demo
        image: wardviaene/k8s-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
