apiVersion: v1
kind: pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: nodehelloworld
    spec:
      containers:
      - name: docker-demo
        image: 1a2k3m/docker-demo
        ports:
          - name: nodejs-ports
          containers: 3000
