apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
    spec:
      containers:
      - name: docker-demo
        image: 1a2k3m/docker-demo
        ports:
          containers: 3000
